import { NextRequest, NextResponse } from "next/server";

import {
  unauthorizedCronResponse,
  verifyCronRequest,
} from "@/lib/cron/auth";
import {
  processDueScheduledPosts,
  processConfirmedQueue,
  autoGenerateDailyDrafts,
} from "@/lib/publishing/publish-post";

async function handleCron(request: NextRequest) {
  try {
    if (!verifyCronRequest(request)) {
      return unauthorizedCronResponse();
    }

    const scheduledSummary = await processDueScheduledPosts();
    const queueSummary = await processConfirmedQueue();
    const autoGenSummary = await autoGenerateDailyDrafts();

    return NextResponse.json({
      success: true,
      data: {
        scheduled: scheduledSummary,
        queue: queueSummary,
        autoGenerated: autoGenSummary,
      },
    });
  } catch (error) {
    const message =
      error instanceof Error
        ? error.message
        : "Unable to process cron tasks";

    return NextResponse.json(
      {
        success: false,
        error: { message, code: "CRON_PUBLISH_FAILED" },
      },
      { status: 500 },
    );
  }
}

export async function GET(request: NextRequest) {
  return handleCron(request);
}

export async function POST(request: NextRequest) {
  return handleCron(request);
}
